-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
--/*
--create table client
--(
--    id   bigserial not null primary key,
--    name varchar(50)
--);
--
-- */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
CREATE sequence hibernate_sequence start WITH 1 increment by 1;

CREATE TABLE address (
    id bigint generated BY DEFAULT AS IDENTITY,
    address VARCHAR(255) not null,
    client_id bigint,
    PRIMARY KEY (id)
    );

CREATE TABLE client (
    id bigint NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE phone (
    id bigint generated BY DEFAULT AS IDENTITY,
    number VARCHAR(255) NOT NULL,
    client_id bigint,
    PRIMARY KEY (id)
    );