-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
/*
create table client
(
    id   bigserial not null primary key,
    name varchar(50)
);

 */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
create sequence hibernate_sequence start with 1 increment by 1;

create table address (
    id bigint generated by default as identity,
    address varchar(255) not null,
    client_id bigint,
    primary key (id)
    )
create table client (
    id bigint not null,
    name varchar(255) not null,
    primary key (id)
    )

create table phone (
    id bigint generated by default as identity,
    number varchar(255) not null,
    client_id bigint,
    primary key (id)
    )