version: '3.9'

services:
  postgres:
    container_name: hw-postgres
    image: postgres:12
    restart: always
    ports:
      - "5430:5432"
#    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "demoDB"
    networks:
      - postgres

  pgadmin:
    container_name: hw-pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "usr"
      PGADMIN_DEFAULT_PASSWORD: "pwd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - postgres

networks:
  postgres:
   driver: bridge

